version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s - %(levelname)-8s - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    error:
        format: "%(asctime)s - %(name)-18s - %(levelname)-8s - %(message)s in %(funcName)s()"
        datefmt: "%Y-%m-%d %H:%M:%S"

    debug:
        format: "%(asctime)s - %(name)-18s  %(levelname)-8s - %(message)s in %(funcName)s()"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    journal_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: service.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8


    # debug_file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: DEBUG
    #     formatter: debug
    #     filename: debug.log
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 20
    #     encoding: utf8

    # error_file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: WARN
    #     formatter: error
    #     filename: errors.log
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 20
    #     encoding: utf8

root:
    level: NOTSET
    handlers: [console]
    propagate: yes

loggers:
    api:
        level: INFO
        # handlers: [console, error_file_handler, debug_file_handler]
        handlers: [console, journal_file_handler]
        propagate: no

